### ISSUE TITLE
Use submodules to pull in m8c

### ISSUE THREAD

**Issue by euphemism** [LeeHolmes/m8_flow#1]
Instead of copying the m8c project code/executable into your repository is it possible to reference it via a submodule? https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by LeeHolmes** [comment]
I don't think so - the project depends on m8c's release executable, not its source.

**Comment by euphemism** [comment]
It would be possible as part of your build process to build m8c from source and then reference the newly built binary, right?

**Comment by LeeHolmes** [comment]
Probably! So far, I'm the only committer and perhaps the only user :) I think I'll have a more refined opinion about proper software engineering if any of that changes :)

**Comment by euphemism** [comment]
Sure thing, thank you for taking the time to entertain the suggestion.
